name: Rector PHP
on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~
jobs:
    rector:
        name: Run rector
        uses: ibexa/gh-workflows/.github/workflows/rector.yml@main
        secrets:
            SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
            SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
            TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
